### ISSUE TITLE
Some request is fail to deserialize automatically using burp extension mode

### ISSUE THREAD

**Issue by grinwood** [vaadata/java-serde#2]
when using this as burp extension, some request are failing to automatically deserialize using this extension
![image](https://github.com/user-attachments/assets/c74407a3-7fb9-4996-b13c-766101ce19fe)
![image](https://github.com/user-attachments/assets/d59f07a4-5203-4bd1-95a0-36e9967dff8d)
![image](https://github.com/user-attachments/assets/b67e2abe-3c70-4d75-95ab-5f5ef49d8078)

**Comment by vaadata-pascala** [comment]
Hi, the Burp extension assumes that the body is compressed using GZIP. It might work if you remove the following lines and rebuild the project.

https://github.com/vaadata/java-serde/blob/f0c9e9e6c4ddc9f01d18d41811ecaea144f82d13/src/main/java/sh/arnaud/javaserde/burp/Editor.java#L52

https://github.com/vaadata/java-serde/blob/f0c9e9e6c4ddc9f01d18d41811ecaea144f82d13/src/main/java/sh/arnaud/javaserde/burp/Editor.java#L72

For the extension, we will add some code in the future to choose a compression strategy based on the beginning of the body.

**Comment by vaadata-pascala** [comment]
Implemented in 8106b8c
